SELECT 
    slug_season, 
    slug_league, 
    type_season,
    RIGHT(slug_season, 2) || '-' || type_season AS year_season_type,
    id_player,
    name_player,
    date_game, 
    id_game, 
    number_game_team_season,
    id_team,
    name_team, 
    slug_team, 
    slug_opponent, 
    slug_team_winner, 
    slug_team_loser, 
    outcome_game,  
    number_game_player_season, 
    minutes,
    fgm, 
    fga, 
    pct_fg, 
    fg3m, 
    fg3a, 
    pct_fg3, 
    pct_ft, 
    fg2m, 
    fg2a, 
    pct_fg2, 
    ftm, 
    fta, 
    oreb, 
    dreb, 
    treb, 
    ast, 
    stl, 
    blk, 
    tov, 
    pf, 
    pts, 
    fpts
FROM nba.player_game_log
WHERE LEFT(SLUG_SEASON, 4)::INT >= 2021
  AND type_season != 'All Star'